/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dat_Le_2;

import Dat_Le.*;
import DatabaseConnection.DatabaseConnect;
import java.awt.Component;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Dat ThinkPad
 */
public class uiHolding_2 extends javax.swing.JFrame {
    
    Statement stmt;
    DatabaseConnect objDBConnect;
    Connection objConnection;
    ResultSet rs;
    String sql;
    
    HashMap<String, String> dataMap;
    HashMap<String, JTextField> txtMap;
    
    DefaultTableModel hoModel;
    Vector header, row, data;
    
    String IDHo, IDGu, IDApa, IDCo, DateHo,FromDateHo, ToDateHo, PayStatusHo, IDSer;
    Double CommissionHo, TotalHo;

    /**
     * Creates new form uiHolding
     */
    public uiHolding_2() 
    {
        initComponents();
        connectToDatabase();
        initData();
        showTable("Select * from Holding");
        modifyTable(tblHo);
    }
    
    public void modifyTable(JTable table)
    {
        table.removeColumn(table.getColumn("Gu"));
        table.removeColumn(table.getColumn("Apa"));
        table.removeColumn(table.getColumn("Co"));
        table.removeColumn(table.getColumn("Commission"));
    }
    
    public void connectToDatabase()
    {
        objDBConnect = new DatabaseConnect();        
        objConnection = objDBConnect.DBConnect("Sem2_project_group2", "sa", "abc123");
        try {
            stmt = objConnection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void initData()
    {
        manageTextField(pHolding);
        manageTextField(pGuest);
        manageTextField(pCollaborator);
    }

    public void manageTextField(JPanel targetPanel)
    {
        Component[] objComponent = targetPanel.getComponents();
        for (Component comp : objComponent) {
            if (comp instanceof JTextField)
            {
                ((JTextField) comp).setText("");
            }
        }
    }
    
    public void manageBtn(boolean btnSearchStatus, boolean btnAddStatus, boolean btnUpdateStatus, boolean btnDeleteStatus)
    {
        btnSearch.setEnabled(btnSearchStatus);
        btnAdd.setEnabled(btnAddStatus);
        btnUpdate.setEnabled(btnUpdateStatus);
        btnDelete.setEnabled(btnDeleteStatus);
    }
    
    public void showTable(String sql)
    {
        hoModel = new DefaultTableModel();
        
        header = new Vector();
        header.add("ID");
        header.add("Gu");
        header.add("Apa");
        header.add("Co");
        header.add("Date");
        header.add("From");
        header.add("To");
        header.add("Status");
        header.add("Total");
        header.add("Commission");
        header.add("Ser");
        
        data = new Vector();
        
        hoModel.setRowCount(0);
        
        try {            
            //select * from Services
            if (sql.isEmpty())                
                sql = "select * from Holding";
            rs = stmt.executeQuery(sql);
            
            rs.beforeFirst();
            while(rs.next())
            {
                row = new Vector();                
                row.add(rs.getString("IDHo"));
                row.add(rs.getString("IDGu"));
                row.add(rs.getString("IDApa"));
                row.add(rs.getString("IDCo"));
                row.add(rs.getString("DateHo"));
                row.add(rs.getString("FromDateHo"));
                row.add(rs.getString("ToDateHo"));
                row.add(rs.getString("PayStatusHo"));
                row.add(rs.getDouble("TotalHo"));
                row.add(rs.getDouble("CommissionHo"));
                row.add(rs.getString("IDSer"));
                data.add(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        hoModel.setDataVector(data, header);
        tblHo.setModel(hoModel);
        //tblBook.setModel(bookModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTblHo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pCollaborator = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        pGuest = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pHolding = new javax.swing.JPanel();
        txtIDHo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtIDGu = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtIDCo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtIDApa = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtDateHo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtFromDateHo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtToDateHo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtPayStatusHo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtCommissionHo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtTotalHo = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnMakeContract = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtIDSer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Holding");

        pTblHo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pTblHo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Holding", "Gu", "Apa", "Co", "Date", "From", "To", "Status", "Total", "Commission", "IDSer"
            }
        ));
        tblHo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHo);

        pTblHo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 42, 438, 115));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Holding Detail");
        pTblHo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 9, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Guest");

        pCollaborator.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField1.setText("jTextField1");

        jLabel3.setText("ID");

        jLabel4.setText("Name");

        jTextField2.setText("jTextField1");

        jTextField3.setText("jTextField1");

        jLabel5.setText("DOB");

        jLabel6.setText("IDNo.");

        jTextField4.setText("jTextField1");

        jTextField6.setText("jTextField1");

        jLabel8.setText("Phone");

        jLabel9.setText("Email");

        jTextField7.setText("jTextField1");

        javax.swing.GroupLayout pCollaboratorLayout = new javax.swing.GroupLayout(pCollaborator);
        pCollaborator.setLayout(pCollaboratorLayout);
        pCollaboratorLayout.setHorizontalGroup(
            pCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCollaboratorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(pCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6)
                    .addComponent(jTextField4)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addGroup(pCollaboratorLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField7))
                .addGap(23, 23, 23))
        );
        pCollaboratorLayout.setVerticalGroup(
            pCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCollaboratorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        pGuest.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField5.setText("jTextField1");

        jLabel7.setText("ID");

        jLabel10.setText("Name");

        jTextField8.setText("jTextField1");

        jTextField9.setText("jTextField1");

        jLabel11.setText("DOB");

        jLabel12.setText("IDNo.");

        jTextField10.setText("jTextField1");

        jTextField11.setText("jTextField1");

        jLabel13.setText("Phone");

        jLabel14.setText("Email");

        jTextField12.setText("jTextField1");

        javax.swing.GroupLayout pGuestLayout = new javax.swing.GroupLayout(pGuest);
        pGuest.setLayout(pGuestLayout);
        pGuestLayout.setHorizontalGroup(
            pGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGuestLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(pGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField11)
                    .addComponent(jTextField10)
                    .addComponent(jTextField8)
                    .addComponent(jTextField9)
                    .addGroup(pGuestLayout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField12))
                .addGap(20, 20, 20))
        );
        pGuestLayout.setVerticalGroup(
            pGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGuestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Collaborator");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pCollaborator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pGuest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pGuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(pCollaborator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        pHolding.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pHolding.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIDHo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIDHo.setText("jTextField1");
        pHolding.add(txtIDHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 13, 197, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("ID");
        pHolding.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 16, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("ID Guest");
        pHolding.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 57, -1, -1));

        txtIDGu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIDGu.setText("jTextField1");
        pHolding.add(txtIDGu, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 54, 197, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("ID Collaborator");
        pHolding.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 98, -1, -1));

        txtIDCo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIDCo.setText("jTextField1");
        pHolding.add(txtIDCo, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 95, 197, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("ID Apartment");
        pHolding.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 139, -1, -1));

        txtIDApa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIDApa.setText("jTextField1");
        pHolding.add(txtIDApa, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 136, 197, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Date");
        pHolding.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 180, -1, -1));

        txtDateHo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDateHo.setText("jTextField1");
        pHolding.add(txtDateHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 177, 197, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("From Date");
        pHolding.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 221, -1, -1));

        txtFromDateHo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFromDateHo.setText("jTextField1");
        pHolding.add(txtFromDateHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 218, 197, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("To Date");
        pHolding.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 262, -1, -1));

        txtToDateHo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtToDateHo.setText("jTextField1");
        pHolding.add(txtToDateHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 259, 197, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Status");
        pHolding.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 340, -1, -1));

        txtPayStatusHo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPayStatusHo.setText("jTextField1");
        pHolding.add(txtPayStatusHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 337, 197, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Commission");
        pHolding.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 381, -1, -1));

        txtCommissionHo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCommissionHo.setText("jTextField1");
        pHolding.add(txtCommissionHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 378, 197, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Total");
        pHolding.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 422, -1, -1));

        txtTotalHo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalHo.setText("jTextField1");
        pHolding.add(txtTotalHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 419, 197, -1));

        btnSearch.setText("Search");
        pHolding.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 453, 144, 57));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        pHolding.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 453, 154, 57));

        btnUpdate.setText("Update");
        pHolding.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 521, 144, 57));

        btnDelete.setText("Delete");
        pHolding.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 521, 154, 57));

        btnMakeContract.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMakeContract.setText("Make Contract");
        pHolding.add(btnMakeContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 584, 341, 68));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Services");
        pHolding.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 303, -1, -1));

        txtIDSer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIDSer.setText("jTextField1");
        pHolding.add(txtIDSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 300, 197, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pTblHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addComponent(pHolding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pHolding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pTblHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblHoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoMouseClicked
        // TODO add your handling code here:
        int row;
        
        row = tblHo.getSelectedRow();
        TableModel tblModel = tblHo.getModel();
        
        IDHo = (String) tblModel.getValueAt(row, 0);       
        IDGu = (String)tblModel.getValueAt(row, 1);
        IDApa = (String)tblModel.getValueAt(row, 2);
        IDCo = (String)tblModel.getValueAt(row, 3);
        DateHo = (String)tblModel.getValueAt(row, 4);
        FromDateHo = (String)tblModel.getValueAt(row, 5);
        ToDateHo = (String)tblModel.getValueAt(row, 6);
        PayStatusHo = (String)tblModel.getValueAt(row, 7);
        TotalHo = (Double)tblModel.getValueAt(row, 8);
        CommissionHo = (Double)tblModel.getValueAt(row, 9);
        IDSer = (String)tblModel.getValueAt(row, 10);
        
        
        txtIDHo.setText(IDHo);
        txtIDGu.setText(IDGu);
        txtIDApa.setText(IDApa);
        txtIDCo.setText(IDCo);
        txtDateHo.setText(DateHo);
        txtFromDateHo.setText(FromDateHo);
        txtToDateHo.setText(ToDateHo);
        txtPayStatusHo.setText(PayStatusHo);
        txtTotalHo.setText(String.valueOf(TotalHo));
        txtCommissionHo.setText(String.valueOf(CommissionHo));
        txtIDSer.setText(IDSer);
        
    }//GEN-LAST:event_tblHoMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uiHolding_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uiHolding_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uiHolding_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uiHolding_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uiHolding_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMakeContract;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel pCollaborator;
    private javax.swing.JPanel pGuest;
    private javax.swing.JPanel pHolding;
    private javax.swing.JPanel pTblHo;
    private javax.swing.JTable tblHo;
    private javax.swing.JTextField txtCommissionHo;
    private javax.swing.JTextField txtDateHo;
    private javax.swing.JTextField txtFromDateHo;
    private javax.swing.JTextField txtIDApa;
    private javax.swing.JTextField txtIDCo;
    private javax.swing.JTextField txtIDGu;
    private javax.swing.JTextField txtIDHo;
    private javax.swing.JTextField txtIDSer;
    private javax.swing.JTextField txtPayStatusHo;
    private javax.swing.JTextField txtToDateHo;
    private javax.swing.JTextField txtTotalHo;
    // End of variables declaration//GEN-END:variables
}
