/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nam;

import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Namcham
 */
public class CollaboratorsManagement extends javax.swing.JFrame {

    Connection connection = null;
    String dbAccount = "sa";
    String dbPassword = "123";
    String dbName = "Sem2_Project_Group2";
    Statement stmt;
    ResultSet rs;
    String sql;

    MainControlInterface mci;

    DefaultTableModel collaboratorsModel;
    Vector header, data, row;
    int dong;
    String id;
    boolean active;
    String path;//duong dan image

    private static String accID;

    /**
     * Creates new form StaffForm
     *
     * @param account
     */
    public CollaboratorsManagement(String account) {
        initComponents();
        setLocationRelativeTo(null);
        pack();
        datechooserCol.setDateFormatString("yyyy-mm-dd");
        try {
            connection = DBConnection.getDBConnection(dbName, dbAccount, dbPassword);
            stmt = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        } catch (Exception e) {
            e.printStackTrace();
        }
        collaboratorsModel = new DefaultTableModel();
        header = new Vector();
        header.add("ID");
        header.add("Full name");
        header.add("Deposit");
        header.add("Phone");
        header.add("Email");

        data = new Vector();
        showTableData();

        accID = account;
    }

    private void showTableData() {
        collaboratorsModel.setRowCount(0);
        try {
            sql = "select * from Collaborator";
            rs = stmt.executeQuery(sql);
            rs.beforeFirst();
            while (rs.next()) {
                row = new Vector();
                row.add(rs.getString("IDCo"));
                row.add(rs.getString("NameCo"));
                //row.add(rs.getString("AdressCo"));
                //row.add(rs.getString("IdentificationNumberCo"));
                row.add(rs.getDouble("DepositCo"));
                row.add(rs.getString("PhoneCo"));
                row.add(rs.getString("EmailCo"));
                //row.add(rs.getString("StatusCo"));
                //row.add(rs.getString("ImageCo"));
                //row.add(rs.getString("DOBCo"));               
                data.add(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        collaboratorsModel.setDataVector(data, header);
        tblCollaborator.setModel(collaboratorsModel);
        setButtonOnOff(false);
        setTextOnOff(false);
        deleteText();
    }

    private void setButtonOnOff(boolean check) {
        btnUpdateCol.setEnabled(check);
        btnBlockCol.setEnabled(check);
        btnUnlockCol.setEnabled(check);
    }

    private void setTextOnOff(boolean check) {
        txtColID.setEditable(check);
        txtColName.setEditable(check);
        datechooserCol.setEnabled(check);
        txtDeposit.setEditable(check);
        txtEmail.setEditable(check);
        txtIdentify.setEditable(check);
        txtNumberofGuest.setEditable(check);
        txtAddress.setEditable(check);
        txtPhone.setEditable(check);
        txtNumberofGuest.setEditable(check);
    }

    private void deleteText() {
        txtColID.setText("");
        txtColName.setText("");
        datechooserCol.setDate(null);
        txtDeposit.setText("");
        txtEmail.setText("");
        txtIdentify.setText("");
        txtNumberofGuest.setText("");
        txtAddress.setText("");
        txtPhone.setText("");
        txtNumberofGuest.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbColManagement = new javax.swing.JLabel();
        lbMin = new javax.swing.JLabel();
        lbClose = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCollaborator = new javax.swing.JTable();
        panelImage = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();
        lbColID = new javax.swing.JLabel();
        lbColName = new javax.swing.JLabel();
        lbColDOB = new javax.swing.JLabel();
        lbColIdentifiedNo = new javax.swing.JLabel();
        lbColDeposit = new javax.swing.JLabel();
        lbColPhone = new javax.swing.JLabel();
        lbColEmail = new javax.swing.JLabel();
        lbColGrade = new javax.swing.JLabel();
        lbColNumberOfGuest = new javax.swing.JLabel();
        txtNumberofGuest = new javax.swing.JTextField();
        txtGrade = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtDeposit = new javax.swing.JTextField();
        txtIdentify = new javax.swing.JTextField();
        txtColName = new javax.swing.JTextField();
        txtColID = new javax.swing.JTextField();
        btnAddNewCol = new javax.swing.JButton();
        btnUpdateCol = new javax.swing.JButton();
        btnBlockCol = new javax.swing.JButton();
        radActive = new javax.swing.JRadioButton();
        radBlock = new javax.swing.JRadioButton();
        btnUnlockCol = new javax.swing.JButton();
        lbColAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        datechooserCol = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        lbColManagement.setBackground(new java.awt.Color(255, 153, 0));
        lbColManagement.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbColManagement.setForeground(new java.awt.Color(255, 255, 255));
        lbColManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbColManagement.setText("Collabarator Management");

        lbMin.setBackground(new java.awt.Color(255, 153, 0));
        lbMin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbMin.setForeground(new java.awt.Color(255, 51, 51));
        lbMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMin.setText("_");
        lbMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMinMouseClicked(evt);
            }
        });

        lbClose.setBackground(new java.awt.Color(255, 153, 0));
        lbClose.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbClose.setForeground(new java.awt.Color(255, 51, 51));
        lbClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbClose.setText("x");
        lbClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lbColManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(lbMin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbClose, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbColManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMin, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbClose, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        tblCollaborator.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCollaborator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCollaboratorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCollaborator);

        javax.swing.GroupLayout panelImageLayout = new javax.swing.GroupLayout(panelImage);
        panelImage.setLayout(panelImageLayout);
        panelImageLayout.setHorizontalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        );
        panelImageLayout.setVerticalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );

        lbColID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbColID.setForeground(new java.awt.Color(255, 255, 255));
        lbColID.setText("Id");

        lbColName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbColName.setForeground(new java.awt.Color(255, 255, 255));
        lbColName.setText("Name");

        lbColDOB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbColDOB.setForeground(new java.awt.Color(255, 255, 255));
        lbColDOB.setText("DOB");

        lbColIdentifiedNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbColIdentifiedNo.setForeground(new java.awt.Color(255, 255, 255));
        lbColIdentifiedNo.setText("Identify No.");

        lbColDeposit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbColDeposit.setForeground(new java.awt.Color(255, 255, 255));
        lbColDeposit.setText("Deposit");

        lbColPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbColPhone.setForeground(new java.awt.Color(255, 255, 255));
        lbColPhone.setText("Phone");

        lbColEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbColEmail.setForeground(new java.awt.Color(255, 255, 255));
        lbColEmail.setText("Email");

        lbColGrade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbColGrade.setForeground(new java.awt.Color(255, 255, 255));
        lbColGrade.setText("Grade");

        lbColNumberOfGuest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbColNumberOfGuest.setForeground(new java.awt.Color(255, 255, 255));
        lbColNumberOfGuest.setText("No. of guests");

        txtNumberofGuest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtGrade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtDeposit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtIdentify.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtColName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtColID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnAddNewCol.setBackground(new java.awt.Color(0, 255, 255));
        btnAddNewCol.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnAddNewCol.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNewCol.setText("Add new");
        btnAddNewCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewColActionPerformed(evt);
            }
        });

        btnUpdateCol.setBackground(new java.awt.Color(255, 255, 0));
        btnUpdateCol.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnUpdateCol.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateCol.setText("Update");

        btnBlockCol.setBackground(new java.awt.Color(255, 0, 51));
        btnBlockCol.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnBlockCol.setForeground(new java.awt.Color(255, 255, 255));
        btnBlockCol.setText("Block");

        buttonGroup1.add(radActive);
        radActive.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radActive.setForeground(new java.awt.Color(255, 255, 255));
        radActive.setText("Active");

        buttonGroup1.add(radBlock);
        radBlock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radBlock.setForeground(new java.awt.Color(255, 255, 255));
        radBlock.setText("Blocked");

        btnUnlockCol.setBackground(new java.awt.Color(51, 255, 51));
        btnUnlockCol.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnUnlockCol.setForeground(new java.awt.Color(255, 255, 255));
        btnUnlockCol.setText("Unblock");

        lbColAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbColAddress.setForeground(new java.awt.Color(255, 255, 255));
        lbColAddress.setText("Address");

        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnBack.setBackground(new java.awt.Color(0, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        datechooserCol.setDateFormatString("yyyy-mm-dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddNewCol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateCol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBlockCol, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUnlockCol, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbColAddress))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbColNumberOfGuest))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(panelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(radActive, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(radBlock)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbColID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbColName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbColDOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbColIdentifiedNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbColDeposit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbColPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbColEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbColGrade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtColID, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtColName, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtIdentify, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtGrade, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtNumberofGuest, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(datechooserCol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(37, 37, 37))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddNewCol, btnBack, btnBlockCol, btnUnlockCol, btnUpdateCol});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {radActive, radBlock});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbColAddress, lbColDOB, lbColDeposit, lbColEmail, lbColGrade, lbColID, lbColIdentifiedNo, lbColName, lbColNumberOfGuest, lbColPhone});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbColID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbColName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbColDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(datechooserCol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbColIdentifiedNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdentify, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbColDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbColPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbColEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbColGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(panelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radActive)
                            .addComponent(radBlock))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumberofGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbColNumberOfGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbColAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBlockCol, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnlockCol)
                    .addComponent(btnUpdateCol)
                    .addComponent(btnAddNewCol)
                    .addComponent(btnBack))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddNewCol, btnBack, btnBlockCol, btnUnlockCol, btnUpdateCol});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lbMinMouseClicked

    private void lbCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCloseMouseClicked
        if (JOptionPane.showConfirmDialog(new JFrame(),
                "Do you want to quit this application ?", "",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_lbCloseMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        mci = new MainControlInterface(accID);
        mci.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblCollaboratorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCollaboratorMouseClicked
        // TODO add your handling code here:
        dong = tblCollaborator.getSelectedRow();
        id = (String) tblCollaborator.getValueAt(dong, 0);

        txtColID.setText(id);
        txtColName.setText((String) tblCollaborator.getValueAt(dong, 1));
        txtDeposit.setText(String.valueOf(tblCollaborator.getValueAt(dong, 2)));
        txtPhone.setText((String) tblCollaborator.getValueAt(dong, 3));
        txtEmail.setText((String) tblCollaborator.getValueAt(dong, 4));

        try {
            sql = "select c.IDCo, c.DOBCo, c.IdentificationNumberCo, c.ImageCo, c.GradeCo, c.NumberOfGuest, c.AddressCo, a.Active from Collaborator c join Account a on c.IDCo = a.ID where c.IDCo = " + "'" + id + "'";
            rs = stmt.executeQuery(sql);
            rs.beforeFirst();
            while (rs.next()) {
                datechooserCol.setDate(rs.getDate("DOBCo"));
                txtGrade.setText(rs.getString("GradeCo"));
                txtIdentify.setText(rs.getString("IdentificationNumberCo"));
                txtAddress.setText(rs.getString("AddressCo"));
                txtNumberofGuest.setText(String.valueOf(rs.getInt("NumberOfGuest")));
                active = rs.getBoolean("Active");
                path = rs.getString("ImageCo");
            }
            if (active) {
                radActive.setSelected(true);
            }
            if (!active) {
                radBlock.setSelected(true);
            }
            ImageIcon colImage = new ImageIcon(path);
            Image img = colImage.getImage();
            Image newImage = img.getScaledInstance(lbImage.getWidth(), lbImage.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon image = new ImageIcon(newImage);
            lbImage.setIcon(image);
        } catch (SQLException ex) {
            Logger.getLogger(CollaboratorsManagement.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tblCollaboratorMouseClicked

    private void btnAddNewColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewColActionPerformed
        // TODO add your handling code here:
        if (btnAddNewCol.getText().equalsIgnoreCase("add new")) {
            setTextOnOff(true);
            deleteText();
            txtColID.grabFocus();
            btnAddNewCol.setText("Save");
        } else {
            //Kiêm tra trang
            if (txtColID.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID cannot be blank. Re-enter.");
                txtColID.grabFocus();
                return;
            }
            if (txtColName.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Name cannot be blank. Re-enter.");
                txtColName.grabFocus();
                return;
            }
            if (txtAddress.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Address cannot be blank. Re-enter.");
                txtAddress.grabFocus();
                return;
            }
            if (txtDeposit.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Deposit cannot be blank. Re-enter.");
                txtDeposit.grabFocus();
                return;
            }
            if (txtEmail.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Email cannot be blank. Re-enter.");
                txtEmail.grabFocus();
                return;
            }
            if (txtGrade.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Grade cannot be blank. Re-enter.");
                txtGrade.grabFocus();
                return;
            }
            if (txtIdentify.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Identification number cannot be blank. Re-enter.");
                txtIdentify.grabFocus();
                return;
            }
            if (txtNumberofGuest.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Number of guest cannot be blank. Re-enter.");
                txtNumberofGuest.grabFocus();
                return;
            }
            if (txtPhone.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Phone cannot be blank. Re-enter.");
                txtPhone.grabFocus();
                return;
            }
            if (datechooserCol.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Date of birth cannot be blank. Re-enter.");
                datechooserCol.grabFocus();
                return;
            }
            int so;
            if (radActive.isSelected()) {
                hasCD = true;
                so = 1;
            } else {
                hasCD = false;
                so = 0;
            }
            sql = "insert into Book values('" + bid + "','" + btitle + "'," + catID + "," + quan + "," + price + "," + so + ")";
            try {
                stmt.executeUpdate(sql);
                row = new Vector();
                row.add(bid);
                row.add(btitle);
                row.add(catID);
                bookModel.addRow(row);
            } catch (Exception e) {
                e.printStackTrace();
            }
            btnAddNewCol.setText("Add New");
            deleteText();
            setButton(false);
            setTextCheck(false);

        }
    }//GEN-LAST:event_btnAddNewColActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CollaboratorsManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CollaboratorsManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CollaboratorsManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CollaboratorsManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CollaboratorsManagement().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewCol;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBlockCol;
    private javax.swing.JButton btnUnlockCol;
    private javax.swing.JButton btnUpdateCol;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser datechooserCol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbClose;
    private javax.swing.JLabel lbColAddress;
    private javax.swing.JLabel lbColDOB;
    private javax.swing.JLabel lbColDeposit;
    private javax.swing.JLabel lbColEmail;
    private javax.swing.JLabel lbColGrade;
    private javax.swing.JLabel lbColID;
    private javax.swing.JLabel lbColIdentifiedNo;
    private javax.swing.JLabel lbColManagement;
    private javax.swing.JLabel lbColName;
    private javax.swing.JLabel lbColNumberOfGuest;
    private javax.swing.JLabel lbColPhone;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbMin;
    private javax.swing.JPanel panelImage;
    private javax.swing.JRadioButton radActive;
    private javax.swing.JRadioButton radBlock;
    private javax.swing.JTable tblCollaborator;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtColID;
    private javax.swing.JTextField txtColName;
    private javax.swing.JTextField txtDeposit;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtIdentify;
    private javax.swing.JTextField txtNumberofGuest;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
