/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nam;

import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Namcham
 */
public class NotificationAdmin extends javax.swing.JDialog {

    Connection conn;
    Statement stmt;
    ResultSet rs;
    String sql;
    DefaultTableModel ColModel;
    Vector header, data, row;

    String continueAccount, continueType;

    String IDCo, nameCo, phoneCo, gradeCo, pathImgCo;
    double depositCo;

    /**
     * Creates new form NotificationAdmin
     *
     * @param parent
     * @param modal
     * @param account
     * @param type
     * @param connnection
     * @param statement
     */
    public NotificationAdmin(java.awt.Frame parent, boolean modal, String account, String type, Connection connnection, Statement statement) {
        super(parent, modal);
        initComponents();
        continueAccount = account;
        continueType = type;
        conn = connnection;
        stmt = statement;
        load();
        setTextOnOff(false);
        pack();
    }
    
//    public void show()
//    {
//        initComponents();
//    }
    
    private void load() {
        ColModel = new DefaultTableModel();
        header = new Vector();
        header.add("ID");
        header.add("Name");
        header.add("Phone");
        header.add("Deposit");
        header.add("Grade");

        data = new Vector();
        ColModel.setRowCount(0);

        sql = "select * from Collaborator where DepositCo < 1000";
        try {
            rs = stmt.executeQuery(sql);
            rs.beforeFirst();
            while (rs.next()) {
                row = new Vector();
                row.add(rs.getString("IDCo"));
                row.add(rs.getString("NameCo"));
                row.add(rs.getString("PhoneCo"));
                row.add(rs.getDouble("DepositCo"));
                row.add(rs.getString("GradeCo"));

                data.add(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(NotificationAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

        ColModel.setDataVector(data, header);
        tbCol.setModel(ColModel);
    }

    private void setTextOnOff(boolean check){
        txtIDCo.setEditable(check);
        txtNameCo.setEditable(check);
        txtGradeCo.setEditable(check);
        txtDepositCo.setEditable(check);
        txtPhoneCo.setEditable(check);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNotification = new javax.swing.JLabel();
        TabbedPane = new javax.swing.JTabbedPane();
        pnelCollaborator = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCol = new javax.swing.JTable();
        lbIDCo = new javax.swing.JLabel();
        lbNameCo1 = new javax.swing.JLabel();
        lbPhoneCo = new javax.swing.JLabel();
        lbDepositCo = new javax.swing.JLabel();
        lbGradeCo = new javax.swing.JLabel();
        txtIDCo = new javax.swing.JTextField();
        txtNameCo = new javax.swing.JTextField();
        txtPhoneCo = new javax.swing.JTextField();
        txtDepositCo = new javax.swing.JTextField();
        txtGradeCo = new javax.swing.JTextField();
        lbImageCo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        lbMessage = new javax.swing.JLabel();
        txtSearchCo = new javax.swing.JTextField();
        btnSearchCo = new javax.swing.JButton();
        btnSendCo = new javax.swing.JButton();
        btnCloseCo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        lbNotification.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbNotification.setForeground(new java.awt.Color(255, 255, 255));
        lbNotification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNotification.setText("Notification");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbNotification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbNotification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TabbedPane.setForeground(new java.awt.Color(255, 0, 51));
        TabbedPane.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        pnelCollaborator.setBackground(new java.awt.Color(102, 102, 102));

        tbCol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbColMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCol);

        lbIDCo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbIDCo.setForeground(new java.awt.Color(255, 255, 255));
        lbIDCo.setText("ID");

        lbNameCo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbNameCo1.setForeground(new java.awt.Color(255, 255, 255));
        lbNameCo1.setText("Name");

        lbPhoneCo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbPhoneCo.setForeground(new java.awt.Color(255, 255, 255));
        lbPhoneCo.setText("Phone");

        lbDepositCo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbDepositCo.setForeground(new java.awt.Color(255, 255, 255));
        lbDepositCo.setText("Deposit");

        lbGradeCo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbGradeCo.setForeground(new java.awt.Color(255, 255, 255));
        lbGradeCo.setText("Grade");

        txtIDCo.setBackground(new java.awt.Color(153, 153, 153));
        txtIDCo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtIDCo.setForeground(new java.awt.Color(255, 255, 255));

        txtNameCo.setBackground(new java.awt.Color(153, 153, 153));
        txtNameCo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNameCo.setForeground(new java.awt.Color(255, 255, 255));

        txtPhoneCo.setBackground(new java.awt.Color(153, 153, 153));
        txtPhoneCo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPhoneCo.setForeground(new java.awt.Color(255, 255, 255));

        txtDepositCo.setBackground(new java.awt.Color(153, 153, 153));
        txtDepositCo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDepositCo.setForeground(new java.awt.Color(255, 255, 255));

        txtGradeCo.setBackground(new java.awt.Color(153, 153, 153));
        txtGradeCo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtGradeCo.setForeground(new java.awt.Color(255, 255, 255));

        lbImageCo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        jScrollPane3.setViewportView(txtMessage);

        lbMessage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbMessage.setForeground(new java.awt.Color(255, 255, 255));
        lbMessage.setText("Message");

        txtSearchCo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnSearchCo.setBackground(new java.awt.Color(0, 255, 204));
        btnSearchCo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchCo.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchCo.setText("Search by ID");

        btnSendCo.setBackground(new java.awt.Color(51, 51, 255));
        btnSendCo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSendCo.setForeground(new java.awt.Color(255, 255, 255));
        btnSendCo.setText("Send");
        btnSendCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendCoActionPerformed(evt);
            }
        });

        btnCloseCo.setBackground(new java.awt.Color(255, 51, 51));
        btnCloseCo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCloseCo.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseCo.setText("Close");
        btnCloseCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseCoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnelCollaboratorLayout = new javax.swing.GroupLayout(pnelCollaborator);
        pnelCollaborator.setLayout(pnelCollaboratorLayout);
        pnelCollaboratorLayout.setHorizontalGroup(
            pnelCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelCollaboratorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnelCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnelCollaboratorLayout.createSequentialGroup()
                        .addGroup(pnelCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(pnelCollaboratorLayout.createSequentialGroup()
                                .addGroup(pnelCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnelCollaboratorLayout.createSequentialGroup()
                                        .addComponent(lbMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnelCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelCollaboratorLayout.createSequentialGroup()
                                                .addComponent(btnSendCo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnCloseCo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnelCollaboratorLayout.createSequentialGroup()
                                        .addComponent(txtSearchCo, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSearchCo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(pnelCollaboratorLayout.createSequentialGroup()
                        .addGroup(pnelCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnelCollaboratorLayout.createSequentialGroup()
                                .addComponent(lbNameCo1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNameCo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnelCollaboratorLayout.createSequentialGroup()
                                .addComponent(lbPhoneCo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPhoneCo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnelCollaboratorLayout.createSequentialGroup()
                                .addComponent(lbIDCo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIDCo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnelCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnelCollaboratorLayout.createSequentialGroup()
                                    .addComponent(lbGradeCo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtGradeCo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnelCollaboratorLayout.createSequentialGroup()
                                    .addComponent(lbDepositCo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDepositCo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(lbImageCo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        pnelCollaboratorLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCloseCo, btnSendCo});

        pnelCollaboratorLayout.setVerticalGroup(
            pnelCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelCollaboratorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnelCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSearchCo)
                    .addComponent(btnSearchCo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(pnelCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnelCollaboratorLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(txtDepositCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnelCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbGradeCo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGradeCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnelCollaboratorLayout.createSequentialGroup()
                        .addGroup(pnelCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbIDCo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnelCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNameCo1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnelCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPhoneCo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhoneCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDepositCo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbImageCo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnelCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelCollaboratorLayout.createSequentialGroup()
                        .addComponent(lbMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnelCollaboratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendCo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCloseCo))
                .addGap(5, 5, 5))
        );

        pnelCollaboratorLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbIDCo, txtDepositCo, txtGradeCo, txtIDCo, txtNameCo, txtPhoneCo});

        pnelCollaboratorLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCloseCo, btnSendCo});

        TabbedPane.addTab("Collaborators", pnelCollaborator);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseCoActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(new JFrame(),
            "Do you want to close ?", "",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        this.dispose();
        }
    }//GEN-LAST:event_btnCloseCoActionPerformed

    private void btnSendCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendCoActionPerformed
        // TODO add your handling code here:
        if (txtMessage.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Message cannot be blank");
            return;
        }

        sql = "insert into " + txtIDCo.getText() + " values ('" + txtMessage.getText() + "', 'unread')";
        try {
            stmt.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(NotificationAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(this, "Message has been sent");
        txtMessage.setText("");
    }//GEN-LAST:event_btnSendCoActionPerformed

    private void tbColMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbColMouseClicked
        // TODO add your handling code here:
        txtMessage.setText("");
        int selectedRow;

        selectedRow = tbCol.getSelectedRow();
        IDCo = (String) tbCol.getValueAt(selectedRow, 0);
        nameCo = (String) tbCol.getValueAt(selectedRow, 1);
        phoneCo = (String) tbCol.getValueAt(selectedRow, 2);
        depositCo = (Double) tbCol.getValueAt(selectedRow, 3);
        gradeCo = (String) tbCol.getValueAt(selectedRow, 4);

        txtIDCo.setText(IDCo);
        txtPhoneCo.setText(phoneCo);
        txtGradeCo.setText(gradeCo);
        txtDepositCo.setText(String.valueOf(depositCo));
        txtNameCo.setText(nameCo);

        sql = "select * from Collaborator where IDCo = '" + IDCo + "'";
        try {
            rs = stmt.executeQuery(sql);
            rs.beforeFirst();
            while (rs.next()) {
                pathImgCo = rs.getString("ImageCo");
            }
        } catch (SQLException ex) {
            Logger.getLogger(NotificationAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

        ImageIcon icon = new ImageIcon(pathImgCo);
        int width = lbImageCo.getWidth();
        int height = lbImageCo.getHeight();
        int icoWidth = icon.getIconWidth();
        int icoHeight = icon.getIconHeight();
        Image image;
        if (icoWidth / icoHeight >= width / height) {
            image = icon.getImage().getScaledInstance(width, icoHeight * width / icoWidth, Image.SCALE_SMOOTH);
        } else {
            image = icon.getImage().getScaledInstance(icoWidth * height / icoHeight, height, Image.SCALE_SMOOTH);
        }

        lbImageCo.setIcon(new ImageIcon(image));
    }//GEN-LAST:event_tbColMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NotificationAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NotificationAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NotificationAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NotificationAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                NotificationAdmin dialog = new NotificationAdmin(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton btnCloseCo;
    private javax.swing.JButton btnSearchCo;
    private javax.swing.JButton btnSendCo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbDepositCo;
    private javax.swing.JLabel lbGradeCo;
    private javax.swing.JLabel lbIDCo;
    private javax.swing.JLabel lbImageCo;
    private javax.swing.JLabel lbMessage;
    private javax.swing.JLabel lbNameCo1;
    private javax.swing.JLabel lbNotification;
    private javax.swing.JLabel lbPhoneCo;
    private javax.swing.JPanel pnelCollaborator;
    private javax.swing.JTable tbCol;
    private javax.swing.JTextField txtDepositCo;
    private javax.swing.JTextField txtGradeCo;
    private javax.swing.JTextField txtIDCo;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextField txtNameCo;
    private javax.swing.JTextField txtPhoneCo;
    private javax.swing.JTextField txtSearchCo;
    // End of variables declaration//GEN-END:variables
}
