/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestMain;

import DatabaseConnection.DatabaseConnect;
import DatabaseConnection.connectionContainer;
import Duy.QuanlyCTV_2;
import Duy.QuanlyOwner_2;
import Tuyet_Duyen.Theme_guest_2;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.SwingUtilities;

/**
 *
 * @author Dat ThinkPad
 */
public class TestMain extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    Dat_Le_2.uiHolding_2 objUIHolding;
    Dat_Le_2.uiContract_2 objUIContract;
    Duy.QuanlyCTV_2 objCTV;
    Duy.QuanlyOwner_2 objOwner;
    Tuyet_Duyen.Services_2 objService;
    Tuyet_Duyen.Theme_guest_2 objThemeGuest;
    Ngoc_Duyen.QLCH.QLCH1 objQLCH;
    String account,type;

    /**
     * Creates new form TestMain
     */
    public TestMain() {
        initComponents();
        //connectSQL();
        account = "Ad01";
        type = "ad";
    }
    
    public void connectSQL()
    {
        DatabaseConnect objDBConnect;
        objDBConnect = new DatabaseConnect();
        connectionContainer connectContainer = objDBConnect.DBConnect(txtDatabase.getText(), txtName.getText(), txtPass.getText(), txtPort.getText());
        
        con = connectContainer.getObjCon();
        stmt = connectContainer.getStatement();
        if (con != null)
            lbStatus.setText("Connected");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDuyenService = new javax.swing.JButton();
        btnDuyenGuest = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDatabase = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        btnDuyCTV = new javax.swing.JButton();
        btnDuyOwner = new javax.swing.JButton();
        btnDatHolding = new javax.swing.JButton();
        btnConnect = new javax.swing.JButton();
        lbStatus = new javax.swing.JLabel();
        btnDatContract = new javax.swing.JButton();
        btnDuyenQLCH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDuyenService.setText("Duyen Service");
        btnDuyenService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuyenServiceActionPerformed(evt);
            }
        });

        btnDuyenGuest.setText("Duyen Guest");
        btnDuyenGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuyenGuestActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Database");

        txtDatabase.setText("Sem2_project_group2");

        jLabel2.setText("Name");

        txtName.setText("sa");

        txtPass.setText("abc123");
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        jLabel3.setText("Pass");

        jLabel4.setText("Port");

        txtPort.setText("1433");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDuyCTV.setText("Duy CTV");
        btnDuyCTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuyCTVActionPerformed(evt);
            }
        });

        btnDuyOwner.setText("Duy Owner");
        btnDuyOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuyOwnerActionPerformed(evt);
            }
        });

        btnDatHolding.setText("Dat Holding");
        btnDatHolding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatHoldingActionPerformed(evt);
            }
        });

        btnConnect.setText("Connect SQL");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        lbStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbStatus.setText("Not Connect");

        btnDatContract.setText("Dat Contract");
        btnDatContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatContractActionPerformed(evt);
            }
        });

        btnDuyenQLCH.setText("Duyen QLCH");
        btnDuyenQLCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuyenQLCHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDuyenService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDuyenGuest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDuyCTV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDuyOwner, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDatHolding, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btnDatContract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnDuyenQLCH, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lbStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConnect)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDuyenService)
                    .addComponent(btnDuyCTV)
                    .addComponent(btnDatHolding)
                    .addComponent(btnDuyenQLCH))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDuyenGuest)
                    .addComponent(btnDuyOwner)
                    .addComponent(btnDatContract))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void btnDuyenServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuyenServiceActionPerformed
        // TODO add your handling code here:
//        SwingUtilities.invokeLater(new Runnable()
//            {
//                public void run()
//                {
//                    //new Tuyet_Duyen.Services_2(con, stmt).setVisible(true);
//                    objService = new Services_2(account, type, con, stmt);
//                    objService.setVisible(true);
//                }
//            }
//        );
    }//GEN-LAST:event_btnDuyenServiceActionPerformed

    private void btnDuyenGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuyenGuestActionPerformed
        // TODO add your handling code here:
        SwingUtilities.invokeLater(new Runnable()
            {
                public void run()
                {
                    //new Tuyet_Duyen.Theme_guest_2(con, stmt).setVisible(true);
                    objThemeGuest = new Theme_guest_2(account, type,con, stmt);
                    objThemeGuest.setVisible(true);
                }
            }
        );
    }//GEN-LAST:event_btnDuyenGuestActionPerformed

    private void btnDuyCTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuyCTVActionPerformed
        // TODO add your handling code here:
        SwingUtilities.invokeLater(new Runnable()
            {
                public void run()
                {
                    objCTV = new QuanlyCTV_2(account, type, con, stmt);
                    objCTV.setVisible(true);
                }
            }        
        );
    }//GEN-LAST:event_btnDuyCTVActionPerformed

    private void btnDuyOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuyOwnerActionPerformed
        // TODO add your handling code here:
        SwingUtilities.invokeLater(new Runnable()
        {
            public void run()
            {
                //new Duy.QuanlyOwner_2(con, stmt).setVisible(true);
                objOwner = new QuanlyOwner_2(account, type, con, stmt);
                objOwner.setVisible(true);
            }
        }        
        );
    }//GEN-LAST:event_btnDuyOwnerActionPerformed

    private void btnDatHoldingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatHoldingActionPerformed
        // TODO add your handling code here:
        SwingUtilities.invokeLater(new Runnable()
        {
            public void run()
            {
                invokeUIHolding();
            }
        }        
        );
    }//GEN-LAST:event_btnDatHoldingActionPerformed

    public void invokeUIHolding()
    {
//        objUIHolding = new uiHolding_2(account, type, con, stmt, this);
//        objUIHolding.setVisible(true);
    }
    
    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        // TODO add your handling code here:
        connectSQL();
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnDatContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatContractActionPerformed
        // TODO add your handling code here:
//        SwingUtilities.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                objUIContract = new uiContract_2(account, type, con, stmt);
//                objUIContract.setVisible(true);
//            }
//        });
    }//GEN-LAST:event_btnDatContractActionPerformed

    private void btnDuyenQLCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuyenQLCHActionPerformed
        // TODO add your handling code here:
//        SwingUtilities.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                objQLCH = new QLCH1(account, type, con, stmt);
//                objQLCH.setVisible(true);
//            }
//        });
    }//GEN-LAST:event_btnDuyenQLCHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnDatContract;
    private javax.swing.JButton btnDatHolding;
    private javax.swing.JButton btnDuyCTV;
    private javax.swing.JButton btnDuyOwner;
    private javax.swing.JButton btnDuyenGuest;
    private javax.swing.JButton btnDuyenQLCH;
    private javax.swing.JButton btnDuyenService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JTextField txtDatabase;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
